EcomerceRazorPages/Pages/Cliente/Carrito/Index.cshtml.cs
using ECommerce.DataAccess.Repository.IRepository;
using ECommerce.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ECommerceRazorPages.Pages.Cliente.Carrito
{
    [Authorize]
    public class IndexModel : PageModel
    {
        public IEnumerable<CarritoCompra> ListaCarritoCompra { get; set; }
        public double TotalCarrito { get; set; } = 0;
        private readonly IUnitOfWork _unitOfWork;
        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public void OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)//valida si hay una persona logeada
            {
                ListaCarritoCompra = _unitOfWork.CarritoCompra.GetAll(
                    filter: u => u.ApplicationUserId == claim.Value,
                    includePropierties: "Producto,Producto.Categoria"
                    );

                foreach (var itemCarrito in ListaCarritoCompra) { 
                    TotalCarrito += (double)(itemCarrito.Producto.Precio * itemCarrito.Cantidad);
                }
            }

        }
        public IActionResult OnPostMas(int carritoId)
        {
            var carrito = _unitOfWork.CarritoCompra.GetFirstOrDefault(c => c.Id == carritoId);
            _unitOfWork.CarritoCompra.IncrementarContador(carrito, 1);
            return RedirectToPage("/Cliente/Carrito/Index");
        }
        public IActionResult OnPostMenos(int carritoId)
        {
            var carrito = _unitOfWork.CarritoCompra.GetFirstOrDefault(c => c.Id == carritoId);
            if(carrito.Cantidad == 1)
            {
                _unitOfWork.CarritoCompra.Remove(carrito);
                _unitOfWork.Save();
            }
            else
            {
                _unitOfWork.CarritoCompra.DecrementarContador(carrito, 1);
            }
            return RedirectToPage("/Cliente/Carrito/Index");
        }
        public IActionResult OnPostEliminar(int carritoId)
        {
            var carrito = _unitOfWork.CarritoCompra.GetFirstOrDefault(c => c.Id == carritoId);
            _unitOfWork.CarritoCompra.Remove(carrito);
            _unitOfWork.Save();
            return RedirectToPage("/Cliente/Carrito/Index");
        }
    }
}

EcomerceRazorPages/Pages/Cliente/Carrito/Resumen.cshtml.cs
using ECommerce.DataAccess.Repository.IRepository;
using ECommerce.Models;
using ECommerce.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

namespace ECommerceRazorPages.Pages.Cliente.Carrito
{
    [Authorize]
    public class ResumenModel : PageModel
    {
        public IEnumerable<CarritoCompra> ListaCarritoCompra { get; set; }
        [BindProperty]
        public Orden Orden { get; set; }
        private readonly IUnitOfWork _unitOfWork;
        public ResumenModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            Orden = new Orden();    
        }
        public void OnGet()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier); // obtiene el usuario
            if (claim != null)//valida si hay una persona logeada
            {
                ListaCarritoCompra = _unitOfWork.CarritoCompra.GetAll(
                    filter: u => u.ApplicationUserId == claim.Value,
                    includePropierties: "Producto,Producto.Categoria"
                    );

                foreach (var itemCarrito in ListaCarritoCompra)
                {
                    Orden.TotalOrden += (double)(itemCarrito.Producto.Precio * itemCarrito.Cantidad);
                }
                //Obtener los datos del usuario del Repositorio de ApplicationUser
                ApplicationUser applicationUser = _unitOfWork.ApplicationUser.
                    GetFirstOrDefault(u => u.Id ==  claim.Value);
                Orden.NombreUsuario = applicationUser.Nombres + " " + applicationUser.Apellidos;
                Orden.DireccionEnvio = applicationUser.Direccion;
                Orden.Telefono = applicationUser.PhoneNumber;
                Orden.InstruccionesAdicionales = Orden.InstruccionesAdicionales;
            }

        }

        public void OnPost()
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier); // obtiene el usuario
            if (claim != null)//valida si hay una persona logeada
            {
                ListaCarritoCompra = _unitOfWork.CarritoCompra.GetAll(
                    filter: u => u.ApplicationUserId == claim.Value,
                    includePropierties: "Producto,Producto.Categoria"
                    );

                foreach (var itemCarrito in ListaCarritoCompra)
                {
                    Orden.TotalOrden += (double)(itemCarrito.Producto.Precio * itemCarrito.Cantidad);
                }
                //Obtener los datos del usuario del Repositorio de ApplicationUser
                ApplicationUser applicationUser = _unitOfWork.ApplicationUser.
                    GetFirstOrDefault(u => u.Id == claim.Value);
                Orden.Estado = CNT.EstadoPendiente;
                Orden.FechaOrden = DateTime.Now;
                Orden.UsuarioId = claim.Value;
                Orden.NombreUsuario = applicationUser.Nombres + " " + applicationUser.Apellidos;
                Orden.DireccionEnvio = Orden.DireccionEnvio;
                Orden.Telefono = Orden.Telefono;
                Orden.InstruccionesAdicionales = Orden.InstruccionesAdicionales;
                _unitOfWork.Orden.Add(Orden);
                _unitOfWork.Save();

                // aqui se agrega detalleOrden
                foreach(var item in ListaCarritoCompra)
                {
                    DetalleOrden detalleOrden = new DetalleOrden()
                    {
                        ProductoId = item.ProductoId,
                        OrdenId = Orden.Id,
                        NombreProducto = item.Producto.Nombre,
                        Precio =  (double)item.Producto.Precio,
                        Cantidad = item.Cantidad
                    };
                    _unitOfWork.DetalleOrden.Add(detalleOrden);
                    _unitOfWork.Save();
                }
                //Limpia el carrito de  compras
                _unitOfWork.CarritoCompra.RemoveRange(ListaCarritoCompra);
                _unitOfWork.Save();
            }

        }
    }
}

EcomerceRazorPages/Pages/Cliente/Inicio/Index.cshtml.cs
using ECommerce.DataAccess.Repository.IRepository;
using ECommerce.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ECommerceRazorPages.Pages.Cliente.Inicio
{
    public class IndexModel : PageModel
    {
        private readonly IUnitOfWork _unitOfWork;
        public IndexModel(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IEnumerable<Producto> Productos { get; set; }
        public void OnGet()
        {
            Productos = _unitOfWork.Producto.GetAll(includePropierties: "Categoria");
        }
    }
}

EcomerceRazorPages/Pages/Cliente/Carrito/Index.cshtml
@page
@model ECommerceRazorPages.Pages.Cliente.Carrito.IndexModel
@{
}
@{
	ViewData["Title"] = "Carrito de Compra";
}


<form method="post">
	<br />
	@if (Model.ListaCarritoCompra.Count() == 0)
	{
		<div>
			Por favor agrega items al carrito de compra
		</div>
	}
	else
	{
		<div class="container">
			<div class="card">
				<div class="card-header bg-dark text-light ml-0 ">
					<div class="row">
						<div class="col-6 pt-2">
							Carrito de Compra
						</div>
						<div class="col-6 text-end">
							<a href="~/Cliente/Inicio/Index" class="btn btn-outline-light btn-sm">Continuar Comprando</a>
						</div>
					</div>
				</div>
				<div class="card-body">
					@foreach (var item in Model.ListaCarritoCompra)
					{
						<div class="row">
							<div class="d-none d-lg-block col-lg-2 text-center py-2">
								<img src="~/productos/@item.Producto.Imagen" class="rounded" width="120" height="80" />
							</div>
							<div class="col-12 text-sm-center text-md-start col-md-5 pt-md-4 ">
								<h4><strong>@item.Producto.Nombre</strong></h4>

								<div class="badge bg-primary text-center" style="font-size:12px;">
									@item.Producto.Categoria.Nombre
								</div>
							</div>
							<div class="col-12 text-sm-center col-md-5 text-md-start row pt-3">
								<div class="col-4 text-md-right pt-md-3" style="padding-top:5px;">
									<h6><strong>$@item.Producto.Precio <span class="text-muted">x</span> @item.Cantidad </strong></h6>
								</div>
								<div class="col-6 col-sm-4 col-lg-6">
									<button type="submit" class="btn btn-primary"
											asp-page-handler="mas" asp-route-carritoId="@item.Id">
										<i class="fa-solid fa-plus"></i>
									</button>
									<button type="submit" class="btn btn-danger"
											asp-page-handler="menos" asp-route-carritoId="@item.Id">
										<i class="fa-solid fa-minus"></i>
									</button>
								</div>
								<div class="col-2 col-sm-4 col-lg-2 text-right">
									<button type="submit" class="btn btn-outline-danger"
											asp-page-handler="eliminar" asp-route-carritoId="@item.Id">
										<i class="fa-solid fa-trash-can"></i>
									</button>
								</div>
							</div>
						</div>

						<hr />
					}

					<div class="row">
						<div class="col-12 col-md-5">
						</div>
						<div class="col-12 col-md-6 offset-md-1 col-lg-4 offset-lg-3 pr-4">
							<ul class="list-group">
								<li class="list-group-item d-flex justify-content-between bg-light">
									<span class="text-info"> Total (USD): $ @Model.TotalCarrito</span>

								</li>
							</ul>
						</div>
					</div>


				</div>
				<div class="card-footer">
					<div class="col-12 col-lg-4 offset-lg-8 col-md-6 offset-md-6">
						<a asp-page="Resumen" class="btn btn-success form-control">Resumen</a>
					</div>
				</div>
			</div>
		</div>
	}
</form>

EcomerceRazorPages/Pages/Cliente/Carrito/Resumen.cshtml
@page
@model ECommerceRazorPages.Pages.Cliente.Carrito.ResumenModel
@{
    ViewData["Title"] = "Resumen";
}
<form method="POST">
    <br />
    <div class="backgroundWhiteBorder">
        <div class="container">
            <div class="card">
                <!-- Header -->
                <div class="card-header bg-dark text-light">
                    <div class="row">
                        <div class="col-6 pt-2">
                            <h3 class="text-white-50">Resumen de Compra</h3>
                        </div>
                        <div class="col-6 text-end">
                            <a asp-page="Index" class="btn btn-outline-info btn-sm">Volver al Carrito</a>
                        </div>
                    </div>
                </div>

                <!-- Body -->
                <div class="card-body">
                    <div class="container rounded p-2">
                        <div class="row">
                            <!-- Información de Envío -->
                            <div class="col-12 col-lg-6 pb-4">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Información de Envío:</span>
                                </h4>
                                <div class="row my-1">
                                    <div class="col-5">
                                        <label>Nombre Completo</label>
                                    </div>
                                    <div class="col-7">
                                        <input asp-for="Orden.NombreUsuario" class="form-control" readonly />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-5">
                                        <label>Teléfono</label>
                                    </div>
                                    <div class="col-7">
                                        <input asp-for="Orden.Telefono" type="tel" class="form-control" readonly  />
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-5">
                                        <label>Dirección</label>
                                    </div>
                                    <div class="col-7">
                                        <textarea data-no-tinymce="true" asp-for="Orden.DireccionEnvio" class="form-control" placeholder="Ingresa tu dirección" required style="height: 100px;" readonly ></textarea>
                                    </div>
                                </div>
                                <div class="row my-1">
                                    <div class="col-5">
                                        <label>Instrucciones Adicionales</label>
                                    </div>
                                    <div class="col-7">
                                        <textarea data-no-tinymce="true" asp-for="Orden.InstruccionesAdicionales" class="form-control" placeholder="Ingresa el mensje que desees" style="height: 80px;"></textarea>
                                    </div>
                                </div>
                            </div>

                            <!-- Resumen del Pedido -->
                            <div class="col-12 col-lg-5 offset-lg-1">
                                <h4 class="d-flex justify-content-between align-items-center mb-3">
                                    <span class="text-info">Detalles del Pedido:</span>
                                </h4>
                                <ul class="list-group mb-3">
                                    <!-- Producto -->
                                    @foreach(var detalle in Model.ListaCarritoCompra){

                                        <li class="list-group-item d-flex justify-content-between">
                                            <div>
                                                <h6 class="my-0">Producto: @detalle.Producto.Nombre</h6>
                                                <small class="text-muted">Cantidad: @detalle.Cantidad</small>
                                            </div>
                                            <span class="text-muted">$ @(detalle.Producto.Precio * detalle.Cantidad)</span>
                                        </li>
                                    
                                    }

                                    <!-- Total -->
                                    <li class="list-group-item d-flex justify-content-between bg-light">
                                        <small class="text-info">Total (USD)</small>
                                        <strong class="text-info">$ @Model.Orden.TotalOrden</strong>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Footer -->
                <div class="card-footer">
                    <div class="row">
                        <div class="col-12 text-end">
                            <button type="submit" id="btnComprar" class="btn btn-success">
                                Confirmar y Comprar
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>